# Generated by Django 4.0.3 on 2022-03-13 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
